/**
 * Dados mock realistas para demo do módulo analista (Luana).
 * Consumidos pelas telas e enviados à API em localhost:8001.
 */

const MOCK_CASES = [
  {
    case_id: '1',
    producer_name: 'Seu Raimundo',
    producer_id: 'p1',
    municipality: 'Itaberaba-BA',
    property_size_ha: 30,
    modulo_fiscal: 1,
    issue_code: 'APP_RIVER_WIDTH',
    days_since_notification: 15,
    days_since_last_contact: 10,
    historical_fix_rate: 0.6,
    channel_reached: 'whatsapp',
    biome: 'Caatinga',
    has_pending_fines: false,
    is_small_property: true,
  },
  {
    case_id: '2',
    producer_name: 'Dona Maria',
    producer_id: 'p2',
    municipality: 'Feira de Santana-BA',
    property_size_ha: 45,
    modulo_fiscal: 2,
    issue_code: 'RL_PERCENTAGE',
    days_since_notification: 22,
    days_since_last_contact: 18,
    historical_fix_rate: 0.4,
    channel_reached: 'sms',
    biome: 'Caatinga',
    has_pending_fines: false,
    is_small_property: true,
  },
  {
    case_id: '3',
    producer_name: 'João Pedro',
    producer_id: 'p3',
    municipality: 'Barreiras-BA',
    property_size_ha: 180,
    modulo_fiscal: 6,
    issue_code: 'APP_SPRING_RADIUS',
    days_since_notification: 8,
    days_since_last_contact: 3,
    historical_fix_rate: 0.2,
    channel_reached: 'whatsapp',
    biome: 'Cerrado',
    has_pending_fines: true,
    is_small_property: false,
  },
  {
    case_id: '4',
    producer_name: 'Ana Cláudia',
    producer_id: 'p4',
    municipality: 'Juazeiro-BA',
    property_size_ha: 22,
    modulo_fiscal: 1,
    issue_code: 'CONSOLIDATED_APP',
    days_since_notification: 35,
    days_since_last_contact: 32,
    historical_fix_rate: 0.5,
    channel_reached: 'none',
    biome: 'Caatinga',
    has_pending_fines: false,
    is_small_property: true,
  },
  {
    case_id: '5',
    producer_name: 'Francisco Lima',
    producer_id: 'p5',
    municipality: 'Vitória da Conquista-BA',
    property_size_ha: 95,
    modulo_fiscal: 3,
    issue_code: 'RL_OVERLAP_UC',
    days_since_notification: 12,
    days_since_last_contact: 5,
    historical_fix_rate: 0.3,
    channel_reached: 'email',
    biome: 'Caatinga',
    has_pending_fines: true,
    is_small_property: true,
  },
  {
    case_id: '6',
    producer_name: 'Pedro Alves',
    producer_id: 'p6',
    municipality: 'Ilhéus-BA',
    property_size_ha: 55,
    modulo_fiscal: 2,
    issue_code: 'APP_LAKE_MARGIN',
    days_since_notification: 28,
    days_since_last_contact: 21,
    historical_fix_rate: 0.7,
    channel_reached: 'whatsapp',
    biome: 'Mata Atlântica',
    has_pending_fines: false,
    is_small_property: true,
  },
  {
    case_id: '7',
    producer_name: 'Lucia Santos',
    producer_id: 'p7',
    municipality: 'Porto Seguro-BA',
    property_size_ha: 12,
    modulo_fiscal: 1,
    issue_code: 'APP_MANGROVE',
    days_since_notification: 5,
    days_since_last_contact: 2,
    historical_fix_rate: 0.8,
    channel_reached: 'whatsapp',
    biome: 'Mata Atlântica',
    has_pending_fines: false,
    is_small_property: true,
  },
  {
    case_id: '8',
    producer_name: 'Carlos Mendes',
    producer_id: 'p8',
    municipality: 'Salvador-BA',
    property_size_ha: 8,
    modulo_fiscal: 1,
    issue_code: 'DOC_MISSING',
    days_since_notification: 40,
    days_since_last_contact: 38,
    historical_fix_rate: 0.1,
    channel_reached: 'sms',
    biome: 'Mata Atlântica',
    has_pending_fines: false,
    is_small_property: true,
  },
  {
    case_id: '9',
    producer_name: 'Rosa Oliveira',
    producer_id: 'p9',
    municipality: 'Jequié-BA',
    property_size_ha: 38,
    modulo_fiscal: 1,
    issue_code: 'PRA_PENDING',
    days_since_notification: 18,
    days_since_last_contact: 14,
    historical_fix_rate: 0.55,
    channel_reached: 'whatsapp',
    biome: 'Caatinga',
    has_pending_fines: true,
    is_small_property: true,
  },
  {
    case_id: '10',
    producer_name: 'Antônio Souza',
    producer_id: 'p10',
    municipality: 'Camaçari-BA',
    property_size_ha: 72,
    modulo_fiscal: 2,
    issue_code: 'RL_LOCATION',
    days_since_notification: 10,
    days_since_last_contact: 7,
    historical_fix_rate: 0.45,
    channel_reached: 'whatsapp',
    biome: 'Mata Atlântica',
    has_pending_fines: false,
    is_small_property: true,
  },
];

const MOCK_ACTIONS = [
  {
    analyst_id: 'luana_01',
    case_id: '1',
    producer_id: 'p1',
    producer_name: 'Seu Raimundo',
    action_type: 'approved',
    issue_code: 'APP_RIVER_WIDTH',
    channel: 'whatsapp',
    timestamp: '2026-06-20T10:00:00',
    days_to_fix: 3,
    fixed: true,
    property_size_ha: 30,
    credit_rural_value_brl: 15000,
  },
  {
    analyst_id: 'luana_01',
    case_id: '1',
    producer_id: 'p1',
    producer_name: 'Seu Raimundo',
    action_type: 'notification_sent',
    issue_code: 'APP_RIVER_WIDTH',
    channel: 'whatsapp',
    timestamp: '2026-06-17T09:00:00',
    days_to_fix: 3,
    fixed: true,
    property_size_ha: 30,
    credit_rural_value_brl: 0,
  },
  {
    analyst_id: 'luana_01',
    case_id: '2',
    producer_id: 'p2',
    producer_name: 'Dona Maria',
    action_type: 'approved',
    issue_code: 'RL_PERCENTAGE',
    channel: 'sms',
    timestamp: '2026-06-18T14:30:00',
    days_to_fix: 5,
    fixed: true,
    property_size_ha: 45,
    credit_rural_value_brl: 22000,
  },
  {
    analyst_id: 'luana_01',
    case_id: '2',
    producer_id: 'p2',
    producer_name: 'Dona Maria',
    action_type: 'notification_sent',
    issue_code: 'RL_PERCENTAGE',
    channel: 'sms',
    timestamp: '2026-06-13T11:00:00',
    days_to_fix: 5,
    fixed: true,
    property_size_ha: 45,
    credit_rural_value_brl: 0,
  },
  {
    analyst_id: 'luana_01',
    case_id: '3',
    producer_id: 'p3',
    producer_name: 'João Pedro',
    action_type: 'call_made',
    issue_code: 'APP_SPRING_RADIUS',
    channel: 'call',
    timestamp: '2026-06-22T16:00:00',
    days_to_fix: 0,
    fixed: false,
    property_size_ha: 180,
    credit_rural_value_brl: 0,
  },
  {
    analyst_id: 'luana_01',
    case_id: '4',
    producer_id: 'p4',
    producer_name: 'Ana Cláudia',
    action_type: 'notification_sent',
    issue_code: 'CONSOLIDATED_APP',
    channel: 'whatsapp',
    timestamp: '2026-06-10T08:45:00',
    days_to_fix: 0,
    fixed: false,
    property_size_ha: 22,
    credit_rural_value_brl: 0,
  },
  {
    analyst_id: 'luana_01',
    case_id: '5',
    producer_id: 'p5',
    producer_name: 'Francisco Lima',
    action_type: 'visit',
    issue_code: 'RL_OVERLAP_UC',
    channel: 'in_person',
    timestamp: '2026-06-19T13:00:00',
    days_to_fix: 0,
    fixed: false,
    property_size_ha: 95,
    credit_rural_value_brl: 0,
  },
  {
    analyst_id: 'luana_01',
    case_id: '6',
    producer_id: 'p6',
    producer_name: 'Pedro Alves',
    action_type: 'approved',
    issue_code: 'APP_LAKE_MARGIN',
    channel: 'whatsapp',
    timestamp: '2026-06-15T10:30:00',
    days_to_fix: 4,
    fixed: true,
    property_size_ha: 55,
    credit_rural_value_brl: 18500,
  },
  {
    analyst_id: 'luana_01',
    case_id: '7',
    producer_id: 'p7',
    producer_name: 'Lucia Santos',
    action_type: 'approved',
    issue_code: 'APP_MANGROVE',
    channel: 'whatsapp',
    timestamp: '2026-06-21T11:15:00',
    days_to_fix: 2,
    fixed: true,
    property_size_ha: 12,
    credit_rural_value_brl: 8000,
  },
  {
    analyst_id: 'luana_01',
    case_id: '8',
    producer_id: 'p8',
    producer_name: 'Carlos Mendes',
    action_type: 'notification_sent',
    issue_code: 'DOC_MISSING',
    channel: 'sms',
    timestamp: '2026-06-05T09:30:00',
    days_to_fix: 0,
    fixed: false,
    property_size_ha: 8,
    credit_rural_value_brl: 0,
  },
  {
    analyst_id: 'luana_01',
    case_id: '9',
    producer_id: 'p9',
    producer_name: 'Rosa Oliveira',
    action_type: 'approved',
    issue_code: 'PRA_PENDING',
    channel: 'whatsapp',
    timestamp: '2026-06-14T15:00:00',
    days_to_fix: 6,
    fixed: true,
    property_size_ha: 38,
    credit_rural_value_brl: 12000,
  },
  {
    analyst_id: 'luana_01',
    case_id: '10',
    producer_id: 'p10',
    producer_name: 'Antônio Souza',
    action_type: 'notification_sent',
    issue_code: 'RL_LOCATION',
    channel: 'whatsapp',
    timestamp: '2026-06-16T10:00:00',
    days_to_fix: 0,
    fixed: false,
    property_size_ha: 72,
    credit_rural_value_brl: 0,
  },
  {
    analyst_id: 'luana_01',
    case_id: '6',
    producer_id: 'p6',
    producer_name: 'Pedro Alves',
    action_type: 'notification_sent',
    issue_code: 'APP_LAKE_MARGIN',
    channel: 'whatsapp',
    timestamp: '2026-06-11T14:00:00',
    days_to_fix: 4,
    fixed: true,
    property_size_ha: 55,
    credit_rural_value_brl: 0,
  },
  {
    analyst_id: 'luana_01',
    case_id: '7',
    producer_id: 'p7',
    producer_name: 'Lucia Santos',
    action_type: 'notification_sent',
    issue_code: 'APP_MANGROVE',
    channel: 'whatsapp',
    timestamp: '2026-06-19T08:30:00',
    days_to_fix: 2,
    fixed: true,
    property_size_ha: 12,
    credit_rural_value_brl: 0,
  },
  {
    analyst_id: 'luana_01',
    case_id: '9',
    producer_id: 'p9',
    producer_name: 'Rosa Oliveira',
    action_type: 'call_made',
    issue_code: 'PRA_PENDING',
    channel: 'call',
    timestamp: '2026-06-08T11:00:00',
    days_to_fix: 6,
    fixed: true,
    property_size_ha: 38,
    credit_rural_value_brl: 0,
  },
  {
    analyst_id: 'luana_01',
    case_id: '1',
    producer_id: 'p1',
    producer_name: 'Seu Raimundo',
    action_type: 'visit',
    issue_code: 'APP_RIVER_WIDTH',
    channel: 'in_person',
    timestamp: '2026-06-01T09:00:00',
    days_to_fix: 3,
    fixed: true,
    property_size_ha: 30,
    credit_rural_value_brl: 0,
  },
];

const MOCK_ERROR_RECORDS = [
  { case_id: '1', issue_code: 'APP_RIVER_WIDTH', producer_id: 'p1', municipality: 'Itaberaba-BA', biome: 'Caatinga', property_size_ha: 30, modulo_fiscal: 1, days_to_fix: 3, fixed: true, fix_attempt_count: 1, channel: 'whatsapp', translated_notification_used: true },
  { case_id: '1', issue_code: 'APP_RIVER_WIDTH', producer_id: 'p1', municipality: 'Itaberaba-BA', biome: 'Caatinga', property_size_ha: 30, modulo_fiscal: 1, days_to_fix: 0, fixed: false, fix_attempt_count: 2, channel: 'sms', translated_notification_used: false },
  { case_id: '2', issue_code: 'RL_PERCENTAGE', producer_id: 'p2', municipality: 'Feira de Santana-BA', biome: 'Caatinga', property_size_ha: 45, modulo_fiscal: 2, days_to_fix: 5, fixed: true, fix_attempt_count: 1, channel: 'sms', translated_notification_used: true },
  { case_id: '2', issue_code: 'RL_PERCENTAGE', producer_id: 'p2', municipality: 'Feira de Santana-BA', biome: 'Caatinga', property_size_ha: 45, modulo_fiscal: 2, days_to_fix: 8, fixed: true, fix_attempt_count: 2, channel: 'whatsapp', translated_notification_used: true },
  { case_id: '3', issue_code: 'APP_SPRING_RADIUS', producer_id: 'p3', municipality: 'Barreiras-BA', biome: 'Cerrado', property_size_ha: 180, modulo_fiscal: 6, days_to_fix: 0, fixed: false, fix_attempt_count: 3, channel: 'email', translated_notification_used: false },
  { case_id: '4', issue_code: 'CONSOLIDATED_APP', producer_id: 'p4', municipality: 'Juazeiro-BA', biome: 'Caatinga', property_size_ha: 22, modulo_fiscal: 1, days_to_fix: 12, fixed: true, fix_attempt_count: 1, channel: 'whatsapp', translated_notification_used: true },
  { case_id: '5', issue_code: 'RL_OVERLAP_UC', producer_id: 'p5', municipality: 'Vitória da Conquista-BA', biome: 'Caatinga', property_size_ha: 95, modulo_fiscal: 3, days_to_fix: 0, fixed: false, fix_attempt_count: 1, channel: 'email', translated_notification_used: true },
  { case_id: '6', issue_code: 'APP_LAKE_MARGIN', producer_id: 'p6', municipality: 'Ilhéus-BA', biome: 'Mata Atlântica', property_size_ha: 55, modulo_fiscal: 2, days_to_fix: 4, fixed: true, fix_attempt_count: 1, channel: 'whatsapp', translated_notification_used: true },
  { case_id: '7', issue_code: 'APP_MANGROVE', producer_id: 'p7', municipality: 'Porto Seguro-BA', biome: 'Mata Atlântica', property_size_ha: 12, modulo_fiscal: 1, days_to_fix: 2, fixed: true, fix_attempt_count: 1, channel: 'whatsapp', translated_notification_used: true },
  { case_id: '8', issue_code: 'DOC_MISSING', producer_id: 'p8', municipality: 'Salvador-BA', biome: 'Mata Atlântica', property_size_ha: 8, modulo_fiscal: 1, days_to_fix: 0, fixed: false, fix_attempt_count: 2, channel: 'sms', translated_notification_used: false },
  { case_id: '9', issue_code: 'PRA_PENDING', producer_id: 'p9', municipality: 'Jequié-BA', biome: 'Caatinga', property_size_ha: 38, modulo_fiscal: 1, days_to_fix: 6, fixed: true, fix_attempt_count: 1, channel: 'whatsapp', translated_notification_used: true },
  { case_id: '10', issue_code: 'RL_LOCATION', producer_id: 'p10', municipality: 'Camaçari-BA', biome: 'Mata Atlântica', property_size_ha: 72, modulo_fiscal: 2, days_to_fix: 7, fixed: true, fix_attempt_count: 1, channel: 'whatsapp', translated_notification_used: true },
  { case_id: '1', issue_code: 'APP_RIVER_WIDTH', producer_id: 'p1', municipality: 'Itaberaba-BA', biome: 'Caatinga', property_size_ha: 30, modulo_fiscal: 1, days_to_fix: 4, fixed: true, fix_attempt_count: 1, channel: 'whatsapp', translated_notification_used: true },
  { case_id: '2', issue_code: 'RL_PERCENTAGE', producer_id: 'p2', municipality: 'Feira de Santana-BA', biome: 'Caatinga', property_size_ha: 45, modulo_fiscal: 2, days_to_fix: 6, fixed: true, fix_attempt_count: 1, channel: 'whatsapp', translated_notification_used: true },
  { case_id: '3', issue_code: 'APP_SPRING_RADIUS', producer_id: 'p3', municipality: 'Barreiras-BA', biome: 'Cerrado', property_size_ha: 180, modulo_fiscal: 6, days_to_fix: 0, fixed: false, fix_attempt_count: 2, channel: 'whatsapp', translated_notification_used: true },
  { case_id: '4', issue_code: 'CONSOLIDATED_APP', producer_id: 'p4', municipality: 'Juazeiro-BA', biome: 'Caatinga', property_size_ha: 22, modulo_fiscal: 1, days_to_fix: 10, fixed: true, fix_attempt_count: 1, channel: 'sms', translated_notification_used: true },
  { case_id: '6', issue_code: 'APP_LAKE_MARGIN', producer_id: 'p6', municipality: 'Ilhéus-BA', biome: 'Mata Atlântica', property_size_ha: 55, modulo_fiscal: 2, days_to_fix: 5, fixed: true, fix_attempt_count: 1, channel: 'in_person', translated_notification_used: false },
  { case_id: '7', issue_code: 'APP_MANGROVE', producer_id: 'p7', municipality: 'Porto Seguro-BA', biome: 'Mata Atlântica', property_size_ha: 12, modulo_fiscal: 1, days_to_fix: 3, fixed: true, fix_attempt_count: 1, channel: 'whatsapp', translated_notification_used: true },
  { case_id: '9', issue_code: 'PRA_PENDING', producer_id: 'p9', municipality: 'Jequié-BA', biome: 'Caatinga', property_size_ha: 38, modulo_fiscal: 1, days_to_fix: 8, fixed: true, fix_attempt_count: 2, channel: 'sms', translated_notification_used: true },
  { case_id: '10', issue_code: 'RL_LOCATION', producer_id: 'p10', municipality: 'Camaçari-BA', biome: 'Mata Atlântica', property_size_ha: 72, modulo_fiscal: 2, days_to_fix: 9, fixed: true, fix_attempt_count: 1, channel: 'whatsapp', translated_notification_used: true },
];

const MOCK_UNIFIED_CASE = {
  case_id: '1',
  producer_name: 'Seu Raimundo',
  producer_id: 'p1',
  municipality: 'Itaberaba-BA',
  property_size_ha: 30,
  biome: 'Caatinga',
  sicar_data: { status: 'pending_retification', car_number: 'BA-1234567-ABC' },
  sigef_data: { overlap_neighbors: 1, conflict_area_ha: 0.5 },
  car_submission_date: '2026-01-15T10:00:00',
  notifications: [
    { timestamp: '2026-02-01T14:00:00', issue_code: 'APP_RIVER_WIDTH', channel: 'whatsapp', translated: true },
    { timestamp: '2026-02-15T09:30:00', issue_code: 'RL_PERCENTAGE', channel: 'sms', translated: true },
  ],
  producer_responses: [
    { timestamp: '2026-02-03T16:20:00', channel: 'whatsapp', content: 'Entendi, vou corrigir no SICAR' },
    { timestamp: '2026-02-18T11:00:00', channel: 'whatsapp', content: 'Preciso de ajuda com a RL' },
  ],
  analyst_actions: [
    { timestamp: '2026-03-01T10:00:00', type: 'rectification', description: 'Retificação submetida pelo produtor' },
    { timestamp: '2026-03-10T15:30:00', type: 'approved', description: 'CAR aprovado após retificação' },
  ],
  sent_messages: [
    { timestamp: '2026-02-01T14:00:00', channel: 'whatsapp', content_summary: 'Notificação APP de rio traduzida', translated_notification_used: true },
    { timestamp: '2026-02-20T10:00:00', channel: 'whatsapp', content_summary: 'Guia passo-a-passo de RL enviado', translated_notification_used: true },
  ],
  received_messages: [
    { timestamp: '2026-02-03T16:20:00', channel: 'whatsapp', content_summary: 'Produtor confirmou que vai corrigir' },
    { timestamp: '2026-02-18T11:00:00', channel: 'whatsapp', content_summary: 'Pedido de ajuda com Reserva Legal' },
  ],
  pending_issues: [{ issue_code: 'APP_RIVER_WIDTH' }],
};

const BENCHMARK = {
  first_try_success_rate: 0.5,
  avg_days_to_fix: 10,
};

/** Filtra ações mock pelo número de dias a partir de hoje. */
function filterActionsByPeriod(actions, days) {
  const cutoff = new Date();
  cutoff.setDate(cutoff.getDate() - days);
  cutoff.setHours(0, 0, 0, 0);
  return actions.filter((a) => new Date(a.timestamp) >= cutoff);
}

/** Deriva registros de erro expandidos para análise de padrões (heatmap/regional). */
function expandErrorRecords(base, multiplier = 4) {
  const expanded = [];
  for (let i = 0; i < multiplier; i++) {
    base.forEach((r, j) => {
      expanded.push({ ...r, case_id: String((j % 10) + 1) });
    });
  }
  return expanded;
}
